server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
          - Path=/restaurants/**
        - id: agent-service
          uri: lb://agent-service
          predicates:
          - Path=/agents/**
        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/orders/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
          - Path=/deliveries/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
          - Path=/ws-notifications/**

logging:
  level:
    '[io.netty]': debug
    '[reactor.netty]': debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka