spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_service
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false

server:
  port: 8085

logging:
  level:
    '[io.netty]': debug
    '[reactor.netty]': debug
    '[reactor.netty.http.client]': debug
    '[org.springframework.web.reactive.function.client.WebClient]': debug
    '[org.apache.http]': debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka